name: todo_workflow

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

  run_format:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run format
        run: npm run format:fix

  run_lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint:fix

  run_test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

  final_lint:
    runs-on: ubuntu-latest
    needs: [run_format, run_lint, run_test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run final lint check
        run: npm run lint
        continue-on-error: true

      - name: Archive lint results
        if: failure()
        run: |
          echo "Linting issues found. Please check the output above for details."
