name: SonarQube Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Start SonarQube
      run: |
        docker-compose up -d
        echo "Waiting for SonarQube to start..."
        while ! curl -s http://localhost:9000 > /dev/null; do
          sleep 5
        done
        echo "SonarQube is up and running"
    
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npm install
        npm run build
        npx sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$SONAR_TOKEN
          
    - name: Check for Blockers
      run: |
        BLOCKERS=$(curl -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/issues/search?componentKeys=${{ github.repository }}&severities=BLOCKER&statuses=OPEN" | jq '.total')
        if [ $BLOCKERS -gt 0 ]; then
          echo "There are $BLOCKERS blocker issues. Failing the workflow."
          exit 1
        fi